apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: devops-platform
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP