apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-platform

resources:
  - ../../base
  - gateway-ingress.yaml
images:
  - name: ghcr.io/juanchogonza98/devops-gateway
    newName: ghcr.io/juanchogonza98/devops-gateway
    newTag: ci-ca502e7b79baaa0dbef5184159aa7720e24d6b94
  - name: devops-orders-service
    newName: ghcr.io/juanchogonza98/devops-orders-service
    newTag: ci-ca502e7b79baaa0dbef5184159aa7720e24d6b94
  - name: devops-payments-service
    newName: ghcr.io/juanchogonza98/devops-payments-service
    newTag: ci-ca502e7b79baaa0dbef5184159aa7720e24d6b94
  - name: devops-products-service
    newName: ghcr.io/juanchogonza98/devops-products-service
    newTag: ci-ca502e7b79baaa0dbef5184159aa7720e24d6b94
  - name: devops-users-service
    newName: ghcr.io/juanchogonza98/devops-users-service
    newTag: ci-ca502e7b79baaa0dbef5184159aa7720e24d6b94

patches:
  - target:
      kind: Deployment
      name: gateway
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: products-service
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: users-service
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: payments-service
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: orders-service
    patch: |-
      - op: add
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always