resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: payments-service-config
    literals:
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - SERVICE_NAME=payments-service